<script setup lang="ts">
/**
 * The logins for the website's JOOX checklist at `/joox-vote`.
 *
 * These are not admin users and carry no role or permission — see the API's `joox-voters`
 * module. All they open is that one page.
 *
 * Passwords are generated by the API and shown here exactly once, in the answer to the call
 * that made them; what the database holds is a bcrypt hash, which nothing can read back. So
 * the screen is built around that one moment: creating an account, and regenerating a
 * password, both end in a dialog with the password in a field ready to copy, and it says
 * plainly that closing it is the end of it. "Forgot the password" has one answer here —
 * generate another.
 */
import { computed, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { http } from '@/api/http';
import { useCrud } from '@/composables/useCrud';
import { confirmDelete } from '@/utils/confirm';
import { PERMISSIONS, type ApiResponse, type JooxVoter, type JooxVoterWithPassword } from '@cms/shared';

const crud = useCrud<JooxVoter>({ endpoint: '/joox-voters' });

// ── Create / edit ─────────────────────────────────────────────────────────────
const dialog = ref(false);
const blank = { id: null as number | null, username: '', displayName: '', isActive: true };
const form = reactive({ ...blank });

const isEdit = computed(() => form.id !== null);
// The username is what the person types to sign in; changing it under them would lock them
// out silently, so it is set once, at creation.
const canSave = computed(() => (isEdit.value ? true : /^[a-zA-Z0-9._-]{3,50}$/.test(form.username)));

/*
 * `row` comes off an Element Plus table slot, which types every row as an open record rather
 * than as the table's own data — so these four take the shape loosely and rely on the column
 * definitions above, the way the rest of the admin's list views do.
 */
function openDialog(row?: JooxVoter | Record<string, any>): void {
  Object.assign(form, blank, row ? { ...row, displayName: row.displayName ?? '' } : {});
  dialog.value = true;
}

/** Creating goes through `http` rather than `useCrud`, because the answer carries a password. */
const saving = ref(false);

async function save(): Promise<void> {
  if (form.id) {
    await crud.updateItem(form.id, {
      displayName: form.displayName.trim() || null,
      isActive: form.isActive,
    });
    dialog.value = false;
    return;
  }

  saving.value = true;
  try {
    const { data } = await http.post<ApiResponse<JooxVoterWithPassword>>('/joox-voters', {
      username: form.username.trim(),
      displayName: form.displayName.trim() || null,
    });
    dialog.value = false;
    await crud.fetchList();
    showPassword(data.data);
  } finally {
    saving.value = false;
  }
}

// ── The one showing of a generated password ───────────────────────────────────
const issued = ref<JooxVoterWithPassword | null>(null);
/** The row whose password is being regenerated, so only its own button spins. */
const resetting = ref<number | null>(null);

function showPassword(result: JooxVoterWithPassword): void {
  issued.value = result;
}

/**
 * `navigator.clipboard` needs a secure context, and an admin panel served over plain HTTP on
 * a LAN is not one — so a failure falls back to selecting the field, which leaves the usual
 * copy gesture to hand rather than a dead button.
 */
const passwordField = ref<{ input?: HTMLInputElement } | null>(null);

async function copyPassword(): Promise<void> {
  const password = issued.value?.password;
  if (!password) return;
  try {
    await navigator.clipboard.writeText(password);
    ElMessage.success('คัดลอกรหัสผ่านแล้ว');
  } catch {
    passwordField.value?.input?.select();
    ElMessage.warning('คัดลอกอัตโนมัติไม่ได้ กรุณากด Ctrl/Cmd + C');
  }
}

async function resetPassword(row: JooxVoter | Record<string, any>): Promise<void> {
  try {
    await ElMessageBox.confirm(
      `สร้างรหัสผ่านใหม่ให้ "${row.username}" ใช่หรือไม่? รหัสผ่านเดิมจะใช้ไม่ได้ทันที และเครื่องที่เข้าสู่ระบบอยู่จะถูกออกจากระบบทั้งหมด`,
      'สร้างรหัสผ่านใหม่',
      { type: 'warning', confirmButtonText: 'สร้างรหัสผ่านใหม่', cancelButtonText: 'ยกเลิก' },
    );
  } catch {
    return;
  }

  resetting.value = row.id;
  try {
    const { data } = await http.post<ApiResponse<JooxVoterWithPassword>>(
      `/joox-voters/${row.id}/password`,
    );
    await crud.fetchList();
    showPassword(data.data);
  } finally {
    resetting.value = null;
  }
}

async function remove(row: JooxVoter | Record<string, any>): Promise<void> {
  const confirmed = await confirmDelete(row.username, {
    note: `ต้องการลบบัญชี "${row.username}" ใช่หรือไม่? บัญชีนี้จะเข้าหน้าโหวตไม่ได้อีก และเครื่องที่เข้าสู่ระบบอยู่จะถูกออกจากระบบทันที`,
  });
  if (!confirmed) return;
  await http.delete(`/joox-voters/${row.id}`);
  ElMessage.success('ลบบัญชีแล้ว');
  await crud.fetchList();
}

function formatDate(value: string | null): string {
  return value ? new Date(value).toLocaleString('th-TH', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
}
</script>

<template>
  <div class="page-container">
    <div class="page-header">
      <h1>บัญชีเข้าใช้หน้าโหวต JOOX</h1>
      <ElButton
        v-permission="PERMISSIONS.JOOX_VOTERS_MANAGE"
        type="primary"
        @click="openDialog()"
      >
        + เพิ่มบัญชี
      </ElButton>
    </div>

    <ElAlert
      class="mb"
      type="info"
      :closable="false"
      show-icon
      title="บัญชีเหล่านี้ใช้เข้าได้เฉพาะหน้า /joox-vote บนเว็บไซต์เท่านั้น ไม่เกี่ยวข้องกับผู้ใช้ที่เข้าระบบ admin"
    />

    <ElCard>
      <div class="toolbar">
        <ElInput
          v-model="crud.query.search"
          placeholder="ค้นหาชื่อผู้ใช้ / ชื่อที่แสดง…"
          clearable
          style="width: 260px"
        />
      </div>

      <ElTable v-loading="crud.loading.value" :data="crud.items.value" @sort-change="crud.onSortChange">
        <ElTableColumn prop="username" label="ชื่อผู้ใช้" min-width="160" sortable="custom" />
        <ElTableColumn label="ชื่อที่แสดง" min-width="160">
          <template #default="{ row }">
            <span v-if="row.displayName">{{ row.displayName }}</span>
            <span v-else class="text-muted">—</span>
          </template>
        </ElTableColumn>
        <ElTableColumn label="สถานะ" width="110" align="center">
          <template #default="{ row }">
            <ElTag size="small" :type="row.isActive ? 'success' : 'info'">
              {{ row.isActive ? 'ใช้งาน' : 'ปิดใช้งาน' }}
            </ElTag>
          </template>
        </ElTableColumn>
        <ElTableColumn label="เข้าใช้ล่าสุด" width="190" prop="lastLoginAt" sortable="custom">
          <template #default="{ row }">{{ formatDate(row.lastLoginAt) }}</template>
        </ElTableColumn>
        <ElTableColumn label="จัดการ" width="260" fixed="right">
          <template #default="{ row }">
            <ElButton size="small" @click="openDialog(row)">แก้ไข</ElButton>
            <ElButton
              v-permission="PERMISSIONS.JOOX_VOTERS_MANAGE"
              size="small"
              :loading="resetting === row.id"
              @click="resetPassword(row)"
            >
              รหัสผ่านใหม่
            </ElButton>
            <ElButton
              v-permission="PERMISSIONS.JOOX_VOTERS_MANAGE"
              size="small"
              type="danger"
              text
              @click="remove(row)"
            >
              ลบ
            </ElButton>
          </template>
        </ElTableColumn>
      </ElTable>

      <ElPagination
        v-model:current-page="crud.query.page"
        class="mt"
        layout="prev, pager, next, total"
        :total="crud.meta.value.total"
        :page-size="crud.query.limit"
      />
    </ElCard>

    <ElDialog v-model="dialog" :title="isEdit ? 'แก้ไขบัญชี' : 'เพิ่มบัญชี'" width="460px">
      <ElForm label-position="top">
        <ElFormItem label="ชื่อผู้ใช้" required>
          <ElInput
            v-model="form.username"
            :disabled="isEdit"
            placeholder="a-z 0-9 . _ - (3–50 ตัวอักษร)"
          />
          <div class="hint">
            {{ isEdit ? 'ชื่อผู้ใช้เปลี่ยนไม่ได้' : 'ตัวพิมพ์เล็ก–ใหญ่ไม่มีผล ระบบจะเก็บเป็นตัวพิมพ์เล็ก' }}
          </div>
        </ElFormItem>
        <ElFormItem label="ชื่อที่แสดง">
          <ElInput v-model="form.displayName" placeholder="เช่น เฟิร์น (ไม่บังคับ)" />
        </ElFormItem>
        <ElFormItem v-if="isEdit">
          <ElCheckbox v-model="form.isActive">เปิดใช้งาน</ElCheckbox>
          <div class="hint">ปิดใช้งานแล้วเครื่องที่เข้าสู่ระบบอยู่จะถูกออกจากระบบทันที</div>
        </ElFormItem>
        <ElAlert
          v-if="!isEdit"
          type="info"
          :closable="false"
          show-icon
          title="ระบบจะสุ่มรหัสผ่านให้อัตโนมัติ และแสดงให้ครั้งเดียวหลังกดบันทึก"
        />
      </ElForm>
      <template #footer>
        <ElButton @click="dialog = false">ยกเลิก</ElButton>
        <ElButton
          type="primary"
          :loading="saving || crud.saving.value"
          :disabled="!canSave"
          @click="save"
        >
          {{ isEdit ? 'บันทึก' : 'สร้างบัญชีและสุ่มรหัสผ่าน' }}
        </ElButton>
      </template>
    </ElDialog>

    <!-- The password, the only time it exists outside this screen. -->
    <ElDialog
      :model-value="issued !== null"
      title="รหัสผ่านใหม่"
      width="440px"
      @update:model-value="issued = null"
    >
      <template v-if="issued">
        <p class="issued-for">
          บัญชี <b>{{ issued.voter.username }}</b>
        </p>
        <ElInput ref="passwordField" :model-value="issued.password" readonly class="password">
          <template #append>
            <ElButton @click="copyPassword">คัดลอก</ElButton>
          </template>
        </ElInput>
        <ElAlert
          class="mt"
          type="warning"
          :closable="false"
          show-icon
          title="คัดลอกและส่งให้ผู้ใช้ก่อนปิดหน้าต่างนี้ — ระบบไม่เก็บรหัสผ่านแบบอ่านได้ ถ้าลืมต้องสุ่มใหม่เท่านั้น"
        />
      </template>
      <template #footer>
        <ElButton type="primary" @click="issued = null">คัดลอกแล้ว ปิดหน้าต่าง</ElButton>
      </template>
    </ElDialog>
  </div>
</template>

<style scoped>
.mt { margin-top: 12px; }
.mb { margin-bottom: 12px; }
.hint { font-size: 12px; color: var(--el-text-color-secondary); line-height: 1.5; }
.issued-for { margin: 0 0 8px; }
.password :deep(input) {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 18px;
  letter-spacing: 1px;
}
</style>
